version: '3'

services:
  image_processor:
    build: .
    environment:
      - CONTENT_DIR=${CONTENT_DIR}
    volumes:
      - ./results:/app/results
      - ${CONTENT_DIR}:/app/content:ro
    tty: true
    stdin_open: true
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]