version: '3'

services:
  image_processor:
    build: .
    volumes:
      - ./:/app
      - ./results:/app/results
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]